src/main/java/com/selina/lending/config/security/clientOAuth2/MiddlewareOAuth2Configuration.java
[LA-109]
[LA-109]: https://selina.atlassian.net/browse/LA-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixed security intersection

src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepository.java, src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryImpl.java, src/main/java/com/selina/lending/internal/service/ProductServiceImpl.java, src/main/java/com/selina/lending/internal/service/RetrieveApplicationServiceImpl.java, src/main/java/com/selina/lending/internal/service/UpdateApplicationServiceImpl.java, src/main/java/com/selina/lending/internal/service/creaditCommitments/UpdateCreditCommitmentsServiceImpl.java, src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryFallbackTest.java, src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryTest.java, src/test/java/com/selina/lending/internal/service/ProductServiceImplTest.java, src/test/java/com/selina/lending/internal/service/RetrieveApplicationServiceImplTest.java, src/test/java/com/selina/lending/internal/service/UpdateApplicationServiceImplTest.java, src/test/java/com/selina/lending/internal/service/creaditCommitments/UpdateCreditCommitmentsServiceImplTest.java
[LA-208]
[LA-208]: https://selina.atlassian.net/browse/LA-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> La 208 patch access fix

src/main/java/com/selina/lending/internal/dto/LendingConstants.java, src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java, src/main/java/com/selina/lending/internal/service/application/domain/ApplicationRequest.java, src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryTest.java
[LA-220] add stage overwrite field with a default value to create DIP request passed to the middleware
[LA-220]: https://selina.atlassian.net/browse/LA-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added stage overwrite field into create dip flow

src/main/java/com/selina/lending/internal/dto/creditcommitments/ApplicantCreditCommitmentsDto.java, src/main/java/com/selina/lending/internal/dto/creditcommitments/UpdateCreditCommitmentsRequest.java, src/test/java/com/selina/lending/api/validator/CCReasonToIgnoreValidationTest.java
[LA-217]
[LA-217]: https://selina.atlassian.net/browse/LA-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LA-217] added ignore+reasonToIgnore compound validation

src/main/java/com/selina/lending/api/errors/ErrorConstants.java, src/main/java/com/selina/lending/api/errors/ExceptionTranslator.java, src/main/java/com/selina/lending/internal/repository/auth/AuthRepositoryImpl.java, src/test/java/com/selina/lending/api/controller/auth/AuthControllerWebApiTest.java, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTestController.java, src/test/java/com/selina/lending/internal/repository/auth/AuthRepositoryImplTest.java
[LA-314] downstream exceptions handling
[LA-314]: https://selina.atlassian.net/browse/LA-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> La 314 downstream exceptions handling

generated/swagger-documentation/lending-api.json, src/main/java/com/selina/lending/api/controller/SwaggerConstants.java, src/main/java/com/selina/lending/api/controller/auth/AuthOperations.java, src/main/java/com/selina/lending/api/errors/ErrorConstants.java, src/main/java/com/selina/lending/api/errors/ExceptionTranslator.java, src/main/java/com/selina/lending/internal/api/AuthApi.java, src/main/java/com/selina/lending/internal/dto/auth/Credentials.java, src/main/java/com/selina/lending/internal/repository/auth/AuthRepositoryImpl.java, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java, src/test/java/com/selina/lending/internal/repository/auth/AuthRepositoryImplTest.java
[LA-316] translate json from error details
[LA-316]: https://selina.atlassian.net/browse/LA-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> La 316 remove json from error details

OWNERS, src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java, src/main/java/com/selina/lending/internal/service/CreateApplicationService.java, src/main/java/com/selina/lending/internal/service/CreateApplicationServiceImpl.java, src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java, src/test/java/com/selina/lending/internal/mapper/MapperBase.java, src/test/java/com/selina/lending/internal/service/CreateApplicationServiceImplTest.java
[GRO-1562](https://selina.atlassian.net/browse/GRO-1562)
[GRO-1562]: https://selina.atlassian.net/browse/GRO-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-1562 filter out declined QuickQuote CC offers

src/main/java/com/selina/lending/internal/dto/IncomeItemDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java, src/test/java/com/selina/lending/api/support/validator/EnumValueImplTest.java
[GRO-1791](https://selina.atlassian.net/browse/GRO-1791)
Applicant's income amount property should be required since it's required on the MW side and the lack of such a property cause the MW to fail with 502 response.
[GRO-1791]: https://selina.atlassian.net/browse/GRO-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-1791: Income amount value is required

.github/pull_request_template.md, src/main/java/com/selina/lending/internal/dto/IncomeItemDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-1568](https://selina.atlassian.net/browse/GRO-1568)
Include frequency enum in incomedto with two values: Monthly or Annually. 
Also included github pr template for better and templated PR descriptions in the future.
[GRO-1568]: https://selina.atlassian.net/browse/GRO-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-1568: include frequency enum in income dto

generated/swagger-documentation/lending-api.json, src/main/java/com/selina/lending/internal/dto/ApplicationDto.java, src/main/java/com/selina/lending/internal/dto/LendingConstants.java, src/main/java/com/selina/lending/internal/dto/OfferDto.java, src/main/java/com/selina/lending/internal/dto/RuleOutcomeDto.java, src/main/java/com/selina/lending/internal/mapper/ApplicationDecisionResponseMapper.java, src/main/java/com/selina/lending/internal/service/CreateApplicationServiceImpl.java, src/main/java/com/selina/lending/internal/service/RetrieveApplicationServiceImpl.java, src/main/java/com/selina/lending/internal/service/application/domain/Offer.java, src/main/java/com/selina/lending/internal/service/application/domain/RuleOutcome.java, src/main/java/com/selina/lending/internal/service/filter/RuleOutcomeFilter.java, src/main/java/com/selina/lending/internal/service/filter/RuleOutcomeFilterImpl.java, src/test/java/com/selina/lending/internal/mapper/ApplicationResponseMapperTest.java, src/test/java/com/selina/lending/internal/mapper/MapperBase.java, src/test/java/com/selina/lending/internal/service/CreateApplicationServiceImplTest.java, src/test/java/com/selina/lending/internal/service/RetrieveApplicationServiceImplTest.java, src/test/java/com/selina/lending/internal/service/filter/RuleOutcomeFilterImplTest.java
Include the rule outcomes for Decline and Refer decisions for DIP applications.
A new decision type of Refer will be returned by decisioning. When the decision is Refer or Decline the rule outcomes will be included in the response for DIP
A new decision field has been added to show the overall decision when we create a new DIP/DIPCC application
Quick quote will only ever return Accept when the decision is declined and mapping is handled downstream
Example response with relevant changes:
```
"requestType": "DIP",
"applicationId": "643e58f529b25171274686b5",
"application": {
"decision": "Decline",
....
"offers": [
{
"id": "b62a8574-1e00-44d1-aeed-5a17ef8e5b4d",
"active": true,
"productFeeCanAdd": false,
"aprc": 0.0,
"cltv": 8.9183,
"offerBalance": 0.0,
"initialTerm": 0,
"initialRate": 8.5, …
```
=> SPEED-50: Add rule outcome filter

src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
**Description**
Bug founded when we send a null primary applicant and a primary applicant
This ticket is in scope of : https://github.com/Selina-Finance/ms-lending-api/pull/180
=> Fix set default primary applicant

src/main/java/com/selina/lending/internal/enricher/ApplicationResponseEnricher.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java, src/test/java/com/selina/lending/internal/enricher/ApplicationResponseEnricherTest.java
We need to add the aggregator path to the applyUrl in the offer.
eg:
---
=> fix(GRO-2057): Add /aggregator path to base URL

src/main/java/com/selina/lending/internal/dto/quote/QuickQuotePropertyDetailsDto.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
Title says all.
Part of the bugs found in bug bash for the release of aggregator work.
=> chore(GRO-2166): add min max validation on estimated value of property

src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java, src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java, src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
=> improvement(GRO-2184): Add reversion payment amount field to QQ response model

src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java, src/main/java/com/selina/lending/internal/dto/quotecf/QuickQuoteCFApplicationRequest.java, src/main/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFRequestMapper.java, src/main/java/com/selina/lending/internal/service/application/domain/quotecf/QuickQuoteCFRequest.java, src/test/java/com/selina/lending/internal/mapper/MapperBase.java, src/test/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFRequestMapperTest.java, src/test/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFResponseMapperTest.java
Ability to specify broker fees for QQ CF applications
=> expect brokerFeesIncluded and brokerFeesUpfront from MW for QQ CF

src/main/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDateImpl.java, src/test/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDateImplTest.java
Any application creation request fails with 500 error when applicant’s address type is not specified.
[GRO-2286](https://selina.atlassian.net/browse/GRO-2286)
[GRO-2286]: https://selina.atlassian.net/browse/GRO-2286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix NPE when applicant's address type is not specified

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
=> fix: Make add to loan fields default to false

src/main/java/com/selina/lending/api/dto/qq/response/ProductOfferDto.java, src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapper.java, src/main/java/com/selina/lending/httpclient/middleware/dto/common/Offer.java, src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapperTest.java
=> feat(GRO-2443): Update models to return netLoanAmount

src/main/java/com/selina/lending/api/dto/common/FeesDto.java, src/main/java/com/selina/lending/api/dto/qq/request/QuickQuoteApplicationRequest.java, src/main/java/com/selina/lending/api/dto/qq/request/QuickQuoteFeesDto.java, src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapper.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapperTest.java
=> feat(GRO-2440): Allows adding Selina arrangement fee to loan

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
=> chore(GRO-2442): Make default values only used if no value is provided

src/main/java/com/selina/lending/api/mapper/qq/middleware/OfferMapper.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
=> fix(GRO-2442): Fix offers mapper

src/main/java/com/selina/lending/api/dto/qq/request/LoanInformationDto.java, src/main/java/com/selina/lending/api/dto/qq/request/QuickQuoteApplicationRequest.java, src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/api/validator/MatchNumberOfApplicantsImpl.java, src/main/java/com/selina/lending/httpclient/selection/dto/request/LoanInformation.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/validator/MatchNumberOfApplicantsImplTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2556](https://selina.atlassian.net/browse/GRO-2556)
[GRO-2557](https://selina.atlassian.net/browse/GRO-2557)
[GRO-2556]: https://selina.atlassian.net/browse/GRO-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-2557]: https://selina.atlassian.net/browse/GRO-2557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2556 and GRO-2557: QQ alternative offers

build.gradle, src/main/resources/application.yaml, src/main/resources/logback-spring.xml
[GRO-2574](https://selina.atlassian.net/browse/GRO-2574)
[GRO-2574]: https://selina.atlassian.net/browse/GRO-2574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-2574): Use Sentry for exception tracking + update logging format

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2564](https://selina.atlassian.net/browse/GRO-2564)
[GRO-2564]: https://selina.atlassian.net/browse/GRO-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2564: Add logic in Lending API to assume that Product and Arrangement Fees are added to the loan at Monevo

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2588](https://selina.atlassian.net/browse/GRO-2588)
**Currently:**
* At the moment Selina only offers a 5 year minimum term
* This means that we can’t offer customers at Experian a 1, 2, 3, or 4 year term
**Desired:**
* HOWEVER, we can receive an application for less than 5 years at Experian and respond with an offer for 5 years. 
* This will mean that we can widen our net and attract more clicks at Experian 🙌
**Solution:**
* If a customer from Experian searches for a loan less than 5 years we overwrite the term to be 5 years prior to sending it to decisioning
[GRO-2588]: https://selina.atlassian.net/browse/GRO-2588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-2588): allow QQ alternative offers requests for Experian

src/main/java/com/selina/lending/api/dto/common/ExpenditureDto.java, src/main/java/com/selina/lending/api/mapper/qq/middleware/ExpenditureMapper.java, src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/httpclient/middleware/dto/qq/request/QuickQuoteRequest.java, src/main/java/com/selina/lending/httpclient/selection/dto/request/Application.java, src/main/java/com/selina/lending/httpclient/selection/dto/request/Expenditure.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/ExpenditureMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapperTest.java
[GRO-2602](https://selina.atlassian.net/browse/GRO-2602)
[GRO-2602]: https://selina.atlassian.net/browse/GRO-2602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Gro 2602 expenditure comeback

src/main/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapper.java, src/main/java/com/selina/lending/httpclient/eligibility/EligibilityApi.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/EligibilityRequest.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/PropertyDetails.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/response/EligibilityResponse.java, src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java, src/main/java/com/selina/lending/repository/EligibilityRepository.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/application.yaml, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/eligibility/EligibilityMapperTest.java, src/test/java/com/selina/lending/repository/EligibilityRepositoryTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java, src/test/resources/application.yml
[GRO-2376](https://selina.atlassian.net/browse/GRO-2376)
[GRO-2376]: https://selina.atlassian.net/browse/GRO-2376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-2376): enrich offers with eligibility value

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/java/com/selina/lending/service/alternativeofferr/AlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/ClearScoreAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/ExperianAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/MonevoAlternativeOfferRequestProcessor.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2616](https://selina.atlassian.net/browse/GRO-2616)
New alternative offer request rules for Monevo:
* if the requestedLoanTerm < 5 then set it to 5
* if the 5 <= requestedLoanTerm < 10  then set it to 10
* if the requestedLoanTerm >= 10 then keep it as it is
[GRO-2616]: https://selina.atlassian.net/browse/GRO-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2616): new alternative offers rules for Monevo

src/main/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapper.java, src/main/java/com/selina/lending/httpclient/eligibility/EligibilityApi.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/Applicant.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/EligibilityRequest.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/Income.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/PropertyDetails.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/response/EligibilityResponse.java, src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java, src/main/java/com/selina/lending/repository/EligibilityRepository.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/application.yaml, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/eligibility/EligibilityMapperTest.java, src/test/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapperTest.java, src/test/java/com/selina/lending/repository/EligibilityRepositoryTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java, src/test/resources/application.yml
[GRO-2656](https://selina.atlassian.net/browse/GRO-2656)
Call the ms-eligibility service to calculate eligibility value passing primary applicant incomes.
[GRO-2656]: https://selina.atlassian.net/browse/GRO-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Gro 2656 call ms eligibility providing applicants incomes

src/main/java/com/selina/lending/api/filter/BrokerRequestKpiFilter.java, src/main/java/com/selina/lending/api/filter/SlaRequestFilter.java, src/main/java/com/selina/lending/config/properties/SlaProperties.java, src/main/resources/application.yaml
[GRO-2595](https://selina.atlassian.net/browse/GRO-2595)
log HTTP requests that breach SLA
[GRO-2595]: https://selina.atlassian.net/browse/GRO-2595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-2595): log HTTP requests that breach SLA

src/main/java/com/selina/lending/exception/RemoteResourceProblemException.java, src/main/java/com/selina/lending/httpclient/middleware/MiddlewareApi.java, src/main/java/com/selina/lending/httpclient/middleware/MiddlewareQQApi.java, src/main/java/com/selina/lending/repository/MiddlewareRepositoryImpl.java, src/main/resources/application.yaml, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java, src/test/java/com/selina/lending/repository/MiddlewareRepositoryTest.java, src/test/resources/application.yml
[GRO-2679](https://selina.atlassian.net/browse/GRO-2679)
[GRO-2679]: https://selina.atlassian.net/browse/GRO-2679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-2679): retry request to the MW to store QQ application after decreased timeout

src/main/java/com/selina/lending/service/enricher/ApplicationResponseEnricher.java, src/test/java/com/selina/lending/service/enricher/ApplicationResponseEnricherTest.java
[GRO-2683](https://selina.atlassian.net/browse/GRO-2683)
[GRO-2683]: https://selina.atlassian.net/browse/GRO-2683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2683): encode applyUrl request params path for Experian only

src/main/java/com/selina/lending/api/dto/dip/request/AdvancedLoanInformationDto.java, src/main/java/com/selina/lending/api/dto/dip/request/ApplicationRequest.java, src/main/java/com/selina/lending/api/dto/dip/request/FacilityDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-2689](https://selina.atlassian.net/browse/GRO-2689)
[GRO-2689]: https://selina.atlassian.net/browse/GRO-2689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2689): validate loan information facilities objects for DIP and DIPCC requests

src/main/java/com/selina/lending/httpclient/eligibility/dto/response/EligibilityResponse.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/response/PropertyInfo.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2692](https://selina.atlassian.net/browse/GRO-2692)
[GRO-2692]: https://selina.atlassian.net/browse/GRO-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2692): use property estimated value from the eligibility response

src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
[GRO-2753](https://selina.atlassian.net/browse/GRO-2753)
[GRO-2753]: https://selina.atlassian.net/browse/GRO-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2753): use Quick Quote Form source for QQ apps created by the ms-quick-quote service

src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
[GRO-2762](https://selina.atlassian.net/browse/GRO-2762)
[GRO-2762]: https://selina.atlassian.net/browse/GRO-2762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2762): map loan info to one facility object

src/main/java/com/selina/lending/api/dto/qq/request/CreditRisk.java, src/main/java/com/selina/lending/api/dto/qq/request/QuickQuoteApplicantDto.java, src/main/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapper.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/CreditRisk.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapperTest.java
[GRO-2779](https://selina.atlassian.net/browse/GRO-2779)
[GRO-2779]: https://selina.atlassian.net/browse/GRO-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2779): allow to specify applicants conduct status for QQ applications

src/main/java/com/selina/lending/api/controller/ExceptionTranslator.java, src/main/java/com/selina/lending/httpclient/middleware/MiddlewareApi.java, src/main/java/com/selina/lending/httpclient/middleware/config/MiddlewareApiErrorDecoder.java, src/main/java/com/selina/lending/httpclient/middleware/dto/error/MiddlewareError.java, src/main/java/com/selina/lending/httpclient/middleware/exception/MiddlewareContactIdIsNoneException.java
[GRO-2806](https://selina.atlassian.net/browse/GRO-2806)
[GRO-2806]: https://selina.atlassian.net/browse/GRO-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2806): reburn Bad Request instead of Internal Server Error when specified unregistered brokerSubmitterEmail

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2814](https://selina.atlassian.net/browse/GRO-2814)
[GRO-2814]: https://selina.atlassian.net/browse/GRO-2814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2814): return only one offer with the lowest APRC value forClearScore only

src/main/java/com/selina/lending/httpclient/selection/dto/response/Product.java, src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/application.yaml, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java, src/test/resources/application.yml
[GRO-2814](https://selina.atlassian.net/browse/GRO-2814)
[GRO-2814]: https://selina.atlassian.net/browse/GRO-2814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2814: filter offers for clearscore

src/main/java/com/selina/lending/api/dto/common/EmploymentDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-2839](https://selina.atlassian.net/browse/GRO-2839)
[GRO-2839]: https://selina.atlassian.net/browse/GRO-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-2839): fix validation for employer name (size must be between 3 and 100)

src/main/java/com/selina/lending/service/alternativeofferr/AlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/ClearScoreAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/ClearScoreExtendedAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/ExperianAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/MonevoAlternativeOfferRequestProcessor.java, src/test/java/com/selina/lending/service/alternativeoffer/ClearScoreAlternativeOfferRequestProcessorTest.java, src/test/java/com/selina/lending/service/alternativeoffer/ClearScoreExtendedAlternativeOfferRequestProcessorTest.java
[GRO-2813](https://selina.atlassian.net/browse/GRO-2813)
[GRO-2813]: https://selina.atlassian.net/browse/GRO-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2813): extended ClearScore alternative offers logic

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/application.yaml, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java, src/test/resources/application.yml
[GRO-2859](https://selina.atlassian.net/browse/GRO-2859)
[GRO-2859]: https://selina.atlassian.net/browse/GRO-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2859): filter offers for Experian

build.gradle, src/main/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapper.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/Decision.java, src/main/java/com/selina/lending/httpclient/eligibility/dto/request/EligibilityRequest.java, src/main/java/com/selina/lending/httpclient/selection/dto/response/FilteredQuickQuoteDecisionResponse.java, src/main/java/com/selina/lending/repository/EligibilityRepository.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapperTest.java, src/test/java/com/selina/lending/repository/EligibilityRepositoryTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2864]( https://selina.atlassian.net/browse/GRO-2864)
[GRO-2864]: https://selina.atlassian.net/browse/GRO-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2864): handle hasReferOffers flag

src/main/java/com/selina/lending/api/dto/common/ExpenditureDto.java, src/main/java/com/selina/lending/api/mapper/common/ExpenditureMapper.java, src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationRequestMapper.java, src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/api/validator/NoControversialExpenditures.java, src/main/java/com/selina/lending/api/validator/NoControversialExpendituresImpl.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java, src/test/java/com/selina/lending/api/mapper/common/ExpenditureMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationRequestMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapperTest.java
[GRO-2887](https://selina.atlassian.net/browse/GRO-2887)
[GRO-2887]: https://selina.atlassian.net/browse/GRO-2887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2887): adjust expenditures frequencies to monthly

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2960](https://selina.atlassian.net/browse/GRO-2960)
[GRO-2960]: https://selina.atlassian.net/browse/GRO-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-2960): add default fees for Experian

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/application.yaml, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java, src/test/resources/application.yml
=> AM-4: Route ms-quick-quote requests to adp if the feature is enabled

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Experian is not ready for the changes, so we need to revert them for a while.
=> Revert "feat(GRO-2960): add default fees for Experian"

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/java/com/selina/lending/util/ABTestUtils.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-2936](https://selina.atlassian.net/browse/GRO-2936)
[GRO-2936]: https://selina.atlassian.net/browse/GRO-2936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2936): A/B pre-approvals test

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
https://selina.atlassian.net/browse/GRO-2859
=> chore(GRO-2859): filter Experian response offers only for GoCompare partner

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/java/com/selina/lending/util/ABTestUtils.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java, src/test/java/com/selina/lending/util/ABTestUtilsTest.java
[GRO-2888](https://selina.atlassian.net/browse/GRO-2888)
[GRO-2888]: https://selina.atlassian.net/browse/GRO-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2888): AB test fixed vs variable rate offers for ClearScore

src/main/java/com/selina/lending/httpclient/adp/AdpGatewayApi.java, src/main/java/com/selina/lending/httpclient/adp/dto/response/QuickQuoteEligibilityDecisionResponse.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
=> AM-30: Filter out Decline offers and update url for eligibility

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/java/com/selina/lending/service/alternativeofferr/AlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/clearscore/ClearScoreAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/experian/ExperianAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/service/alternativeofferr/monevo/MonevoAlternativeOfferRequestProcessor.java, src/main/java/com/selina/lending/util/ABTestUtils.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-3053](https://selina.atlassian.net/browse/GRO-3053)
[GRO-3053]: https://selina.atlassian.net/browse/GRO-3053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-3035): turn off offers on 5 years tem searches at Experian (A/B test)

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-3109](https://selina.atlassian.net/browse/GRO-3109)
=> chore(GRO-3109): filter only Variable rate lowest APRC offer for Experian CreditMatcher partner

src/main/java/com/selina/lending/api/controller/SwaggerConstants.java, src/main/java/com/selina/lending/api/dto/common/EmploymentDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-3105](https://selina.atlassian.net/browse/GRO-3105)
[GRO-3105]: https://selina.atlassian.net/browse/GRO-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-3105): allow the 1700-01-01 as the earliest date for all date fields

src/main/java/com/selina/lending/api/dto/common/EmploymentDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-3128](https://selina.atlassian.net/browse/GRO-3128)
[GRO-3128]: https://selina.atlassian.net/browse/GRO-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-3128): allow applicants employer name to be 2 characters long

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/application.yaml, src/test/resources/application.yml
=> AM-309: Add feature flag for enabling ADP

src/main/java/com/selina/lending/api/dto/dip/request/DIPPropertyDetailsDto.java, src/main/java/com/selina/lending/api/dto/dipcc/request/DIPCCPropertyDetailsDto.java, src/main/java/com/selina/lending/api/dto/qq/request/QuickQuotePropertyDetailsDto.java, src/main/java/com/selina/lending/httpclient/middleware/dto/common/PropertyDetails.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/common/PropertyDetailsMapperTest.java
[GRO-3183](https://selina.atlassian.net/browse/GRO-3183)
[GRO-3183]: https://selina.atlassian.net/browse/GRO-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-3183): delete hasAGarage excess property

src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapperTest.java, src/test/java/com/selina/lending/api/mapper/qqcf/QuickQuoteCFResponseMapperTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-3203](https://selina.atlassian.net/browse/GRO-3203)
[GRO-3203]: https://selina.atlassian.net/browse/GRO-3203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-3203): return declined QQ response when there are no accepted offers after products filtration

src/main/java/com/selina/lending/service/alternativeofferr/experian/ExperianCreditMatcherAlternativeOfferRequestProcessor.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
[GRO-3243](https://selina.atlassian.net/browse/GRO-3243)
[GRO-3243]: https://selina.atlassian.net/browse/GRO-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-3243):  apply A/B test GRO-3053 group B logic to credit matcher only
