Selina-Finance/ms-lending-api

src/main/java/com/selina/lending/api/interceptor/BrokerRequestResolver.java, src/main/java/com/selina/lending/messaging/event/BrokerRequestKpiEvent.java, src/main/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapper.java, src/test/java/com/selina/lending/api/interceptor/BrokerRequestResolverTest.java, src/test/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapperTest.java
[LA-154] add request/response to the kpi event
[LA-154]: https://selina.atlassian.net/browse/LA-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
I refactored the mapper a little bit to open the possibility to parse requests/responses of different requests
Here I do value KISS over DRY as the main idea.
Actually, it is possible to separate QQ and DIP into different mapper beans, but I decided to leave them in a single bean as a compromise variant
=> La 154 add req resp to kpi event

src/main/java/com/selina/lending/internal/mapper/OfferMapper.java, src/main/java/com/selina/lending/internal/mapper/quotecc/OfferMapper.java, src/main/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapper.java, src/test/java/com/selina/lending/internal/mapper/MapperBase.java, src/test/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapperTest.java
**Description**
Map fields of a class to another with different names.
```
offers[].productCode -> offers[].code 
offers[].product -> offers[].name 
```
**Background Context**
In quickquotecc, lending api make a request to MW. 
MW response  is mapped to Lending API /quickquotecc response
However current Lending API /quickquotecc response have this fields with another names
**Additional Information**
Ticket: https://selina.atlassian.net/browse/GRO-1788
=> GRO-1788: map missing fields missing quickquotecc

src/main/java/com/selina/lending/internal/mapper/quotecc/OfferMapper.java, src/test/java/com/selina/lending/internal/mapper/MapperBase.java, src/test/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapperTest.java
**Description**
Its misssing map one field of MW response to QuickQuoteCC Response
`offers[].productFeeAddedToLoan -> offers[].hasProductFeeAddedToLoan 
`
**Background Context**
In quickquotecc, lending api make a request to MW.
MW response is mapped to Lending API /quickquotecc response
However current Lending API /quickquotecc response have this field with another name
**Additional Information**
Ticket: https://selina.atlassian.net/browse/GRO-1789
=> GRO-1789: Map missed field from MW response

src/main/java/com/selina/lending/internal/dto/IncomeDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-1585](https://selina.atlassian.net/browse/GRO-1585)
Add conditional validation for expectsFutureIncomeDecreaseReason.
If expectsFutureIncomeDecrease is true then the expectsFutureIncomeDecreaseReason must be one of the following enum values provided.
Integrate with Ocean Finance.
[GRO-1585]: https://selina.atlassian.net/browse/GRO-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-1585: validation for expectsFutureIncomeDecrease and reason

src/main/java/com/selina/lending/internal/dto/IncomeDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-1793](https://selina.atlassian.net/browse/GRO-1793)
While creating an application via the Lending API we can specify each applicant's income information. This income object must not be null.
Also, we have a subobject here with the same name which is a list of income we want to specify. This list might be empty, but the whole object can not be null, because the MW expects to get it even if the list doesn't have any income element inside.
```
],
"income": {  // <<<<<<< must not be null
"income": [   // <<<<<<< must not be null, but it can be an empty list
{
"type": "string",
"amount": 0
}
],
"doesNotHaveAnyIncome": true,
"expectsFutureIncomeDecrease": true,
"expectsFutureIncomeDecreaseReason": "string",
"contractDayRateVerified": 0,
"contractDaysWorkedWeeklyVerified": 0
},
``` …
=> GRO-1793: income list object must not be null

src/main/java/com/selina/lending/internal/enricher/ApplicationResponseEnricher.java, src/test/java/com/selina/lending/internal/enricher/ApplicationResponseEnricherTest.java
add conditional to check whether or not the offers list is null before enriching the response with applyUrl.
Was breaking in production because sometimes the offers list would come back as null from decisioning.
=> fix npe raised when offers comes as null

src/main/java/com/selina/lending/internal/service/application/domain/Offer.java, src/main/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapper.java, src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
In the scope of the [PR-174](https://github.com/Selina-Finance/ms-lending-api/pull/174) I forgot to map the "propertyValuation" field.
=> map offer propertyValueation to a Kafka event

src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java, src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java
[GRO-2133](https://selina.atlassian.net/browse/GRO-2133)
While the Lending API requests the MW to create DIP applications it should provide in a request body
* applicants[].identifier=1 (instead of 0) if the primaryApplicant=true
* applicants[].identifier=2 (instead of 1) if the primaryApplicant=false
because the MW [expects](https://github.com/Selina-Finance/ms-middleware-api/blob/main/middleware/credit_commitments/application_mapper.py#L54) only 1 and 2 values
[GRO-2133]: https://selina.atlassian.net/browse/GRO-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2133: applicant's identifier is 1 for primaty applicants and is 2 for secondary

src/main/java/com/selina/lending/api/support/validator/LessThanOrEqualTo.java, src/main/java/com/selina/lending/api/support/validator/LessThanOrEqualToImpl.java, src/main/java/com/selina/lending/internal/dto/PriorChargesDto.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java, src/test/java/com/selina/lending/internal/mapper/MapperBase.java, src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryTest.java
Creating the DIP application we can specify prior charges object
```
"priorCharges": {
"balanceConsolidated": 0,
"balanceOutstanding": 0,
"monthlyPayment": 0,
"priorChargesYoungestDate": "2001-01-01",
"otherDebtPayments": 0
}
```
We need to provide additional validation that:
* all properties can’t be less than zero
* balanceConsolidated must be less or equal to balanceOutstanding
Ticket [GRO-2248](https://selina.atlassian.net/browse/GRO-2248)
[GRO-2248]: https://selina.atlassian.net/browse/GRO-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2248: additional validation of property details prior charges

src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/httpclient/middleware/dto/common/Fees.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Title says basically all. We need to enrich the requests to decision and the Middleware save with more fields with default values.
Before this is merged, another piece of work on ms-selection needs to be merged first to add the missing field `addArrangementFeeSelinaToLoan` and start sending to decision-v2.
---
=> chore(GRO-2313): Add method to enrich request with default fees values

src/main/java/com/selina/lending/api/controller/QuickQuoteController.java, src/main/java/com/selina/lending/service/enricher/ApplicationResponseEnricher.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java, src/test/java/com/selina/lending/service/enricher/ApplicationResponseEnricherTest.java
[GRO-2388](https://selina.atlassian.net/browse/GRO-2388)
We need this hack only for ClearScore because they provide estimatedValue in response, but because of the hack in the decisioning service (that returns only the lovest LTV offers) the final response is not real, so it’s like isAprcHeadline=true, but we provide isAprcHeadline=false.
So, until we have the dynamic pricing released we need this hack to be working.
[GRO-2388]: https://selina.atlassian.net/browse/GRO-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2388: set each offer's isAprcHeadline=true while creating QQ for the ClearScore only

src/main/java/com/selina/lending/api/dto/common/IncomeItemDto.java
[GRO-2371](https://selina.atlassian.net/browse/GRO-2371)
Current
Aggregator customers using the /quickquote endpoint can specify incomes as being Monthly, or Annually in frequency
Desired
Data from Monevo shows that a fair proportion of customers (10%) enter their data as having Weekly frequency
Hence, we would like the API to be able to accept and accurately process incomes with a weekly frequency
[GRO-2371]: https://selina.atlassian.net/browse/GRO-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-2371: Allow aggregators to provide incomes on a weekly frequency

src/main/java/com/selina/lending/api/dto/common/IncomeItemDto.java, src/main/java/com/selina/lending/httpclient/middleware/dto/common/Income.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
[GRO-2371](https://selina.atlassian.net/browse/GRO-2371)
Since the income.frequency is not used anywhere it should be deleted from the API
[GRO-2371]: https://selina.atlassian.net/browse/GRO-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Gro 2371 delete income frequency field

src/main/java/com/selina/lending/config/security/SecurityConfig.java, src/test/java/com/selina/lending/api/controller/DIPControllerCircuitBreakerTest.java, src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java, src/test/java/com/selina/lending/api/controller/auth/AuthControllerWebApiTest.java, src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java
[GRO-2471](https://selina.atlassian.net/browse/GRO-2471)
The Lending API requires a CSRF token in case of a request without an Authorization header
```
{
"title": "Forbidden",
"status": 403,
"detail": "Could not verify the provided CSRF token because no token was found to compare."
}
```
However, in that case, a response should be Unauthorized, but not Forbidden.
That happens because in security settings the CSRF protection is enabled. Since the service does not provide any web pages and is supposed to be called only by other services there is no need to have a CSRF protection at all.
The correct response should be
```
{
"title": "Unauthorized",
"status": 401,
"detail": "Full authentication is required to access this resource"
}
```
[GRO-2471]: …
=> GRO-2471: Disable CSRF protection

src/main/java/com/selina/lending/api/mapper/qq/middleware/ExpenditureMapper.java, src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapper.java, src/main/java/com/selina/lending/httpclient/middleware/dto/qq/request/QuickQuoteRequest.java, src/main/java/com/selina/lending/httpclient/selection/dto/request/Application.java, src/main/java/com/selina/lending/httpclient/selection/dto/request/Expenditure.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java, src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapperTest.java
Title says most of it. The objective is to start sending expenditures to both ms-selection and ms-middleware-api.
eg:
---
=> improvement(GRO-2442): Add missing expenditure models

src/main/java/com/selina/lending/api/controller/QuickQuoteController.java, src/main/java/com/selina/lending/service/enricher/ApplicationResponseEnricher.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java, src/test/java/com/selina/lending/service/enricher/ApplicationResponseEnricherTest.java
Since the dynamic pricing functionality has been released there is no more need for that hack described in the [GRO-2388: [ms-lending-api] set each offer's isAprcHeadline=true while creating QQ for the ClearScore only](https://selina.atlassian.net/browse/GRO-2388)
=> GRO-2550: do not override each offer's isAprcHeadline=true while creating QQ for the ClearScore only

src/main/java/com/selina/lending/httpclient/middleware/dto/qqcf/request/QuickQuoteCFRequest.java, src/main/java/com/selina/lending/service/CreateApplicationServiceImpl.java, src/test/java/com/selina/lending/api/mapper/MapperBase.java, src/test/java/com/selina/lending/service/CreateApplicationServiceImplTest.java
[GRO-1984](https://selina.atlassian.net/browse/GRO-1984)
While calling the MW /application/quote_broker endpoint provide the next new request body params:
the new string root level “sourceType“ request body param
the new floating root level “fees.arrangementFeesDiscount“ request body param
These values should be taken from the information stored in Keycloak in the scope of the GRO-1975: [keycloak] in the "broker-client" realm specify the new "sourceType" access token claim
DONE
Return in a response the new floating “arrangementFee“ value for each offer.
[GRO-1984]: https://selina.atlassian.net/browse/GRO-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-1984): Enrich request with needed data before sending to Middleware

.gitignore, src/main/java/com/selina/lending/service/alternativeofferr/MonevoAlternativeOfferRequestProcessor.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
According to the last update, we should apply the following alternative offer rules for Monevo clients only
* if the 1 <= requestedLoanTerm <= 4 set it to 5
* if the  5 <= requestedLoanTerm <= 10 set it to 10
* if the requestedLoanTerm > 10 use the original value
=> fix(GRO-2616): fix new alternative offer reules for Monevo

src/main/java/com/selina/lending/service/enricher/ApplicationResponseEnricher.java, src/test/java/com/selina/lending/service/enricher/ApplicationResponseEnricherTest.java
Unfortunately, the agreed fix will not help, so it wasn't released and the changes were reverted.
We are waiting for the fix on their side.
So, this PR reverts these changes [GRO-2683](https://selina.atlassian.net/browse/GRO-2683)
[GRO-2683]: https://selina.atlassian.net/browse/GRO-2683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2683): revert - encode applyUrl request params path for Experian only

src/main/java/com/selina/lending/api/dto/common/ExpenditureDto.java, src/main/java/com/selina/lending/api/dto/dip/request/ApplicationRequest.java, src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java, src/test/java/com/selina/lending/api/validator/EnumValueImplTest.java
[GRO-2725](https://selina.atlassian.net/browse/GRO-2725)
While creating applications via the Lending API service if at least one expenditure item is specified it must contain both properties:
* expenditureType
* amountDeclared
[GRO-2725]: https://selina.atlassian.net/browse/GRO-2725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-2725): fix expenditure validation

src/main/java/com/selina/lending/httpclient/middleware/config/MiddlewareApiErrorDecoder.java
Sometimes the service gets the following errors
```
[timestamp=2024-01-05T10:08:53.410Z] [level=ERROR] [traceId=f389a5d7fbd14f9f] [spanId=f389a5d7fbd14f9f] [version=0.13.11] [source=c.s.l.h.m.c.MiddlewareApiErrorDecoder   :43] [thread=[nio-8080-exec-9]] : Error deserializing the Middleware response [response=feign.httpclient.ApacheHttpClient$1@6cd78832]
```
that means the Middleware service replied with unexpected error response. In order to see that error response we need to log it.
=> refactor(errorLogging): log Middleware error responses

src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationRequestMapper.java, src/main/java/com/selina/lending/httpclient/adp/dto/request/PriorCharges.java, src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java, src/main/resources/logback-spring.xml, src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationRequestMapperTest.java, src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
When we get a declined response, we should return a simple decline response with no offers so that it mimicks what the existing selection service is doing.
eg:
---
=> ST-2150: Return a Decline response with no offers

src/main/java/com/selina/lending/api/dto/common/OfferDto.java, src/test/java/com/selina/lending/api/mapper/qq/middleware/OfferMapperTest.java
[GRO-2894](https://selina.atlassian.net/browse/GRO-2894)
Expose offers netLoanAmound for DIP with Prior charges and DIP CC applications
[GRO-2894]: https://selina.atlassian.net/browse/GRO-2894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-2894): expose netLoanAmount for DIP and DIPCC applications
